# Generated by Django 2.0.2 on 2018-03-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.TextField(blank=True, db_column='Food', null=True)),
                ('type1', models.TextField(blank=True, db_column='Type', null=True)),
                ('calories', models.IntegerField(blank=True, db_column='Calories', null=True)),
            ],
        ),
    ]
