# Generated by Django 2.0.2 on 2018-03-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table1',
            new_name='foodb',
        ),
    ]
